apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"twistlock-defender-ds","namespace":"twistlock"},"spec":{"selector":{"matchLabels":{"app":"twistlock-defender"}},"template":{"metadata":{"annotations":{"container.apparmor.security.beta.kubernetes.io/twistlock-defender":"unconfined"},"labels":{"app":"twistlock-defender"}},"spec":{"containers":[{"env":[{"name":"WS_ADDRESS","value":"wss://twistlock-console:8084"},{"name":"DEFENDER_TYPE","value":"cri"},{"name":"LOG_PROD","value":"true"},{"name":"SYSTEMD_ENABLED","value":"false"},{"name":"DOCKER_CLIENT_ADDRESS","value":"/var/run/docker.sock"},{"name":"DEFENDER_CLUSTER_ID","value":"5dc89b86-860b-5d0b-f4ca-841e72930d3a"},{"name":"DEFENDER_CLUSTER_NAME_RESOLVING_METHOD","value":"default"},{"name":"DEFENDER_CLUSTER","value":""},{"name":"MONITOR_SERVICE_ACCOUNTS","value":"true"},{"name":"MONITOR_ISTIO","value":"false"},{"name":"COLLECT_POD_LABELS","value":"false"},{"name":"INSTALL_BUNDLE","value":"eyJzZWNyZXRzIjp7fSwiZ2xvYmFsUHJveHlPcHQiOnsiaHR0cFByb3h5IjoiIiwibm9Qcm94eSI6IiIsImNhIjoiIiwidXNlciI6IiIsInBhc3N3b3JkIjp7ImVuY3J5cHRlZCI6IiJ9fSwibWljcm9zZWdDb21wYXRpYmxlIjpmYWxzZX0="},{"name":"HOST_CUSTOM_COMPLIANCE_ENABLED","value":"false"},{"name":"CLOUD_HOSTNAME_ENABLED","value":"false"},{"name":"FIPS_ENABLED","value":"false"}],"image":"registry-auth.twistlock.com/tw_wgdhemeo0dlxlflyhtmeob8uo4t1ffky/twistlock/defender:defender_33_01_137","name":"twistlock-defender","resources":{"limits":{"cpu":"900m","memory":"512Mi"},"requests":{"cpu":"256m"}},"securityContext":{"capabilities":{"add":["NET_ADMIN","NET_RAW","SYS_ADMIN","SYS_PTRACE","SYS_CHROOT","MKNOD","SETFCAP","IPC_LOCK"]},"privileged":false,"readOnlyRootFilesystem":true},"volumeMounts":[{"mountPath":"/var/lib/twistlock","name":"data-folder"},{"mountPath":"/var/lib/twistlock/certificates","name":"certificates"},{"mountPath":"/var/run","name":"docker-sock-folder"},{"mountPath":"/etc/passwd","name":"passwd","readOnly":true},{"mountPath":"/dev/log","name":"syslog-socket"},{"mountPath":"/var/lib/containerd","name":"cri-data"},{"mountPath":"/var/lib/rancher/rke2/agent/containerd","name":"cri-rke2-data"},{"mountPath":"/run","name":"runc-proxy-sock-folder"}]}],"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true,"hostPID":true,"restartPolicy":"Always","serviceAccountName":"twistlock-service","volumes":[{"name":"certificates","secret":{"defaultMode":256,"secretName":"twistlock-secrets"}},{"hostPath":{"path":"/dev/log"},"name":"syslog-socket"},{"hostPath":{"path":"/var/lib/twistlock"},"name":"data-folder"},{"hostPath":{"path":"/etc/passwd"},"name":"passwd"},{"hostPath":{"path":"/var/run"},"name":"docker-sock-folder"},{"hostPath":{"path":"/var/lib/containerd"},"name":"cri-data"},{"hostPath":{"path":"/var/lib/rancher/rke2/agent/containerd"},"name":"cri-rke2-data"},{"hostPath":{"path":"/run"},"name":"runc-proxy-sock-folder"}]}}}}
    creationTimestamp: "2024-12-06T22:43:13Z"
    generation: 1
    name: twistlock-defender-ds
    namespace: twistlock
    resourceVersion: "109346680"
    uid: 3404598d-bbbb-472b-9adb-84f6555b2aa0
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: twistlock-defender
    template:
      metadata:
        annotations:
          container.apparmor.security.beta.kubernetes.io/twistlock-defender: unconfined
        creationTimestamp: null
        labels:
          app: twistlock-defender
      spec:
        containers:
        - env:
          - name: WS_ADDRESS
            value: wss://twistlock-console:8084
          - name: DEFENDER_TYPE
            value: cri
          - name: LOG_PROD
            value: "true"
          - name: SYSTEMD_ENABLED
            value: "false"
          - name: DOCKER_CLIENT_ADDRESS
            value: /var/run/docker.sock
          - name: DEFENDER_CLUSTER_ID
            value: 5dc89b86-860b-5d0b-f4ca-841e72930d3a
          - name: DEFENDER_CLUSTER_NAME_RESOLVING_METHOD
            value: default
          - name: DEFENDER_CLUSTER
          - name: MONITOR_SERVICE_ACCOUNTS
            value: "true"
          - name: MONITOR_ISTIO
            value: "false"
          - name: COLLECT_POD_LABELS
            value: "false"
          - name: INSTALL_BUNDLE
            value: eyJzZWNyZXRzIjp7fSwiZ2xvYmFsUHJveHlPcHQiOnsiaHR0cFByb3h5IjoiIiwibm9Qcm94eSI6IiIsImNhIjoiIiwidXNlciI6IiIsInBhc3N3b3JkIjp7ImVuY3J5cHRlZCI6IiJ9fSwibWljcm9zZWdDb21wYXRpYmxlIjpmYWxzZX0=
          - name: HOST_CUSTOM_COMPLIANCE_ENABLED
            value: "false"
          - name: CLOUD_HOSTNAME_ENABLED
            value: "false"
          - name: FIPS_ENABLED
            value: "false"
          image: registry-auth.twistlock.com/tw_wgdhemeo0dlxlflyhtmeob8uo4t1ffky/twistlock/defender:defender_33_01_137
          imagePullPolicy: IfNotPresent
          name: twistlock-defender
          resources:
            limits:
              cpu: 900m
              memory: 512Mi
            requests:
              cpu: 256m
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
              - SYS_PTRACE
              - SYS_CHROOT
              - MKNOD
              - SETFCAP
              - IPC_LOCK
            privileged: false
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/twistlock
            name: data-folder
          - mountPath: /var/lib/twistlock/certificates
            name: certificates
          - mountPath: /var/run
            name: docker-sock-folder
          - mountPath: /etc/passwd
            name: passwd
            readOnly: true
          - mountPath: /dev/log
            name: syslog-socket
          - mountPath: /var/lib/containerd
            name: cri-data
          - mountPath: /var/lib/rancher/rke2/agent/containerd
            name: cri-rke2-data
          - mountPath: /run
            name: runc-proxy-sock-folder
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        hostPID: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: twistlock-service
        serviceAccountName: twistlock-service
        terminationGracePeriodSeconds: 30
        volumes:
        - name: certificates
          secret:
            defaultMode: 256
            secretName: twistlock-secrets
        - hostPath:
            path: /dev/log
            type: ""
          name: syslog-socket
        - hostPath:
            path: /var/lib/twistlock
            type: ""
          name: data-folder
        - hostPath:
            path: /etc/passwd
            type: ""
          name: passwd
        - hostPath:
            path: /var/run
            type: ""
          name: docker-sock-folder
        - hostPath:
            path: /var/lib/containerd
            type: ""
          name: cri-data
        - hostPath:
            path: /var/lib/rancher/rke2/agent/containerd
            type: ""
          name: cri-rke2-data
        - hostPath:
            path: /run
            type: ""
          name: runc-proxy-sock-folder
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 2
    desiredNumberScheduled: 2
    numberAvailable: 2
    numberMisscheduled: 0
    numberReady: 2
    observedGeneration: 1
    updatedNumberScheduled: 2
kind: List
metadata:
  resourceVersion: ""